[build]
command = "npm install"

publish = "docs"

functions = "netlify/functions"

# This redirects all API calls starting with /api/ to the Netlify functions
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[functions."aggregate-pr"]
timeout = 60